version: "3.9"
   
services:
  postgres:
    image: postgres
    container_name: tracle_local_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tracle_beta
      - POSTGRES_USER=tracle
      - POSTGRES_PASSWORD=tracle
  
  redis:
    image: redis
    container_name: tracle_local_redis
  
  django:
    build: 
      context: .
      dockerfile: ./compose/local/Dockerfile
    container_name: tracle_local_django
    env_file: ./envs/local.env
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    command: /start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  
  mailhog:
    image: mailhog/mailhog
    container_name: tracle_local_mailhog
    ports:
      - "8025:8025"

volumes:
  postgres_data:
