version: "3.9"
   
services:
  redis:
    image: redis
    container_name: tracle_prod_redis
  
  django:
    build: 
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: tracle_prod_django
    container_name: tracle_prod_django
    env_file: ./envs/production.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: /start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
